

    create table tb_concorrente (
        id bigint generated by default as identity,
        cpf varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table tb_lance (
        valor float(53),
        concorrente_id bigint,
        id bigint generated by default as identity,
        leilao_id bigint,
        primary key (id)
    );

    create table tb_leilao (
        leilao_status integer,
        valor_minimo float(53),
        id bigint generated by default as identity,
        descricrao varchar(255),
        primary key (id)
    );

    alter table if exists tb_lance 
       add constraint FKolj2prm0snw1tbi1011ud41f0 
       foreign key (concorrente_id) 
       references tb_concorrente;

    alter table if exists tb_lance 
       add constraint FKjymg5ksx7wbvvon45kjhlo1ck 
       foreign key (leilao_id) 
       references tb_leilao;
