

    create sequence audit_log_seq start with 1 increment by 50;

    create table audit_log (
        id bigint not null,
        timestamp timestamp(6),
        event_name varchar(50) not null unique,
        affected_resource varchar(255),
        event_description varchar(255),
        origin varchar(255),
        user_id varchar(255),
        primary key (id)
    );

    create table role (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity,
        username varchar(15) not null unique,
        email varchar(255) not null unique,
        password varchar(255),
        role varchar(255),
        primary key (id)
    );

    create table user_role (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    alter table if exists user_role 
       add constraint FKa68196081fvovjhkek5m97n3y 
       foreign key (role_id) 
       references role;

    alter table if exists user_role 
       add constraint FK859n2jvi8ivhui0rl0esws6o 
       foreign key (user_id) 
       references user;
